package com.tincan.telepathiccaller.entities;

import java.util.ArrayList;

import com.tincan.telepathiccaller.R;

public class Profiles {
	ArrayList<Profile> profiles = new ArrayList<Profile>();
	
	public Profiles() {
		profiles.add(new Profile(1, "Aloof Dromedary", "Wandering the desert, you don't make contact often at all. Must be hard getting reception in the desert.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(2, "Cynical Aardvark", "On those rare occasions you have run out of ants for lunch you might make a call, but otherwise you'd rather not hear someone’s voice", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(3, "Voiceless Polar Bear", "You have your close friends but they don't hear from you often, you would rather hunt seal.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(4, "Afraid Bunny", "You might be a professional at trying to look cute but you are afraid of the dark. Who wouldn't be? The dark is scary…", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(5, "Abashed Cougar", "Normally a predator you shy away from view, striking at night when people least expect it.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(6, "Utopian Mongoose", "You have the rare burst of energy in the morning which you find is the best time to strike", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(7, "Raspy Ibex", "Quiet and conceded, you only rarely make contact on the weekends for something to eat", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(8, "Highfalutin Alligator", "You spend most of your time alone because no one is as awesome as you.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(9, "Exclusive Dessert Spoon", "Stored in a cupboard, you only come out for special events and dinner parties", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(10, "Parsimonious Bunny", "Afraid of spending money on even trivial things, you only make calls when you are in a bind", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(11, "Nebulous Coffee Pot", "Occasionally you make calls in the morning to a select few but at least it wakes them up", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(12, "Royal Bumblebee", "You come down from your throne only occasionally to contact your exclusive friends.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(13, "Narrow Frog", "You know what you when and when to do it. You just mostly can't be bothered.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(14, "Ethereal Pig", "Having reached enlightenment, you find time is best spend rolling in mud and organising dinner", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(15, "Childlike Lovebird", "Your calling habits are beginning to mature but you still remain cautious", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(16, "Young Rainbow", "Still learning how to shine, you aren't ready to face the world just yet. Perhaps it just doesn't rain often enough.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(17, "Jazzy Hairspray", "Not to be used too often, your just use your phone for special occasions on the weekend. Stuck in the 80's perhaps?", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(18, "Tartan Scooter", "You avoid using your phone too often to avoid ridicule. I mean really, who puts tartan on a scooter.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(19, "Questionable Fishstick", "Much like last night left-over’s sometime it isn't always a good idea to put your phone in the microwave.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(20, "Typical Panda", "You make the occasional phone call to your closest friends but only when fresh out of bamboo.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(21, "Adorable Jam", "A regular at the breakfast table, there is nothing like a good phone call to start the day. Just make sure it isn't confused for toast.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(22, "Forgetful Otter", "If you have to call the same person often clearly it's because you have forgotten something. Or was it… I can't remember.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(23, "Auspicious Pirate Ship", "In the past people thought of pirate ships as a bad sign, so that makes you very confusing. Make up your mind dammit.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(24, "Secretive Hippopotamus", "You make the most of your phone calls around dinner during the week; this can only mean you are up to something. I don't trust hippos.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(25, "Hilarious Fox", "The night brings you alive (or at least, your phone). Calling close friends and loved ones, it certainly makes the days more bearable.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(26, "Gleaming Apple", "An apple a day might keep the doctor away but you tend to just have them on weekends. You are an early starter and like letting others know about it.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(27, "Dramatic Sock Puppet", "Sock puppets are awesome, especially dramatic ones. Your prime time is midday on the weekends; people are most receptive to sock puppets at this time.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(28, "Lewd Snake", "Hiding in the long grass, you are surprisingly social for a snake, you like to get out there and sort out your meals early. Just watch for people with shovels.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(29, "Bawdy Koala", "Koalas are well known for their vulgar jokes are you are no exception. Perhaps a bit less Eucalyptus next weekend?", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(30, "Habitual Chinchilla", "You like to call your close friends regularly and use the cover of night to help conceal your whereabouts. Someone is after your fur and you know it.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(31, "Domineering Wombat", "You are like a crazed wombat, waking up early and frequently calling people. Surely a wombat isn't the most appropriate alarm clock", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(32, "Typical Walrus", "Being a walrus you love to have a good chat around lunchtime. It is impressive how you use a phone with flippers.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(33, "Tough Bandaid", "I don't even know how it's relevant to your calling habits; perhaps you get hurt a lot on the phone. It's really not my place to say.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(34, "Exultant Lovebird", "For those you love to call you call them frequently. Around dinner time during the week is where you like the spread your wings.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(35, "Romantic Zebu", "You can't help listening to love songs on the radio and calling friends during those lonely weeknights. It's ok; you are a Zebu after all.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(36, "Guttural Trombone", "The last thing most people want to hear on the weekend in the morning is a trombone, but you insist on frequently calling them anyway.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(37, "Adhesive Wolf", "Things are frequently sticking to your fur and you can' help but call people and tell them about it. This tends to happen around lunch time during the week", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(38, "Alluring Chair", "It's on those easy weekend afternoons that your get into full relaxed mode and begin giving your phone a full work out.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(39, "Sordid Spatula", "Spatulas have a long history of moral distaste and you are no exception. Weekend dinners are your favourite time to spread your contempt.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(40, "Classy Wildcat", "At night on the weekend is when you are in full stride, bringing your classy nature to only those who deserve to hear it.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(41, "Didactic Chicken", "All chickens like telling people what to do, especially early in the morning. Only difference is you do it a lot more than others…", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(42, "Impartial Gila", "You have an intense focus when it comes to phone calls but you remain objective. You maintain balance by making phone calls around lunchtime, the safest time of day.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(43, "Elated Ferret", "A king among ferrets. You are your busiest on weekday afternoons, making an insane number of calls to those you deem worthy.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(44, "Wicked Wine Rack", "If it's in the evening on a weekday, you can be sure to find you on the phone and usually to the same group of people.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(45, "Comfortable Panther", "Not all the time though, but when it's dark on a weeknight you are totally alive, calling like mad.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(46, "Onerous Elf", "Everybody loves elves but when you make all those calls on the weekend in the mornings it can be a bit of chore for the recipient.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(47, "Incandescent Hog", "When you eat lunch you light up the room. And by light up the room I mean vigorously call your friends and family.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(48, "Oafish Stallion", "On those crazy weekend afternoon your go a little wild, knocking things around and making an intense amount of calls. At least you keep the damage localised.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(49, "Labored Pony", "While others are busy eating dinner you are still hard at work, making phone calls like they are going out of fashion.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(50, "Groovy Alpaca", "Alpaca are usually quite groovy already, but you are significantly more groovy than normal, you also enjoy telling people about it. A lot.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.FOCUSSED_CALLER));
		profiles.add(new Profile(51, "Dirty Diphthong", "Why so dirty? Perhaps those rare but early morning calls aren't as appreciated as people pretend…", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(52, "Majestic Chicken", "Chickens can't use phones and you are no exception. But clearly your plumage is more important.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(53, "Functional Turtle", "You only make calls when it's totally necessary, if it doesn't provide a purpose why bother, right?", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(54, "Sedate Boar", "You would sleep all day and night but occasionally you realise you need to eat.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(55, "Nervous Toad", "Like any smart toad you avoid contact with any potential threat, using the cover of darkness to make your move.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(56, "Obsolete Rabbit", "You've been replaced with a newer, more advanced rabbit. Or at least that is how you treat your phone. Talking on mobiles is totally 2009.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(57, "Tricky Panda", "Most pandas wouldn't know how to use a mobile phone, but on those rare occasions you are out of bamboo you find the power to do it.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(58, "Elite Truck", "You call a normal range of people, just not very often. Too much time spent on the road perhaps?", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(59, "Offbeat Spoon", "Spoons have been a well known musical instrument for centuries; you just seem to be out of time. Practise more, I believe in you.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(60, "Abnormal Coati", "You are quite a bit shyer than your average Coati, making only the rare phone call on weeknights.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(61, "Soggy Cereal", "That’s no doubt what you find when making the occasional call early in the morning.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(62, "Adamant Wombat", "Making only the occasional on a weekday during lunch, when you make a call you can sure it is because you mean it.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(63, "Nonchalant Beaver", "You'll make the occasional call on a lazy weekday afternoon, perhaps to organise dinner or some dam building", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(64, "Whispering Wine Cooler", "Breaking out the phone like the occasional wine you like to call people around dinner during the week. Call responsibly.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(65, "Lovely Chinchilla", "You only make occasional calls on weeknights but it's always appreciated when you do call. Everyone loves Chinchillas.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(66, "Abashed Chimpanzee", "Being a chimpanzee can be embarrassing. You just keep it simple with the occasional morning call on the weekend", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(67, "Youthful Champagne", "You love your weekends and sitting down to a good drink, no matter what it is!", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(68, "Rebel Warthog", "Being such a rebel you won't often be found on the phone. Perhaps too busy singing and hanging out with a meerkat", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(69, "Educated Futon", "Most futons wouldn't a clue what's going on, but you have it all worked out. This is probably why you don't use your phone much.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(70, "Psychedelic Mole", "You are far more interested in partying then making phone calls. Being a mole is so groovy.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(71, "Healthy Blender", "You like to keep your calling habits regular and fit, getting that early bird's worm and washing it down with a smoothie.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(72, "Silly Finger Puppet", "Filly puppets are silly by nature, so you are just doing what comes naturally. Nothing to be ashamed of.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(73, "Spiffy Wrench", "Wow, how spiffy is this phone? It's like a wrench, only you wouldn't hit someone with it. Could use a clean though.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(74, "Cultured Alpaca", "You are a social creature; you enjoy hanging with the herd and having something to eat. You’re most busy time is dinner, any day of the week", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(75, "Meek Marmoset", "Marmosets have never been known for their outgoing behaviour and same goes for your phone call behaviour. You save your calls for the cover of darkness but you still find time to make them regularly.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(76, "Perfect Donkey", "Donkeys aren't well known for being intelligent which is what makes you perfect. You only do it an average amount but calling people on the weekends in the morning isn't exactly prime time.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(77, "Decorous Bird", "You make most your calls around midday during the week so you are rarely waking anyone up. How thoughtful.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(78, "Righteous Chipmunk", "You know where it's at and when. You are a chipmunk with the right stuff. You keep your calls to the weekends and keep things well moderated.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(79, "Boundless Gopher", "With no restrictions you have broken free of the standard gopher routine and have found the ability to use a phone. What a talented gopher you are.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(80, "Filthy Rainbow Sticker", "Once upon a time you were shining bright but now you have spent too much time out on weekends and could probably do with a wash.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(81, "Gainful Whale", "You fire up bring and early on weekday mornings, making frequent use of your phone. The early bird gets the… plankton?", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(82, "Entertaining Horse", "While other horses are busy eating hay during the week you are out there entertaining the masses and you do it frequently.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(83, "Friendly Stallion", "You make a lot of calls but you try and make them at reasonable times of day.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(84, "Friendly Yak", "Around dinner time during the week you can't help being yourself and getting on the phone to tell everyone the latest gossip.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(85, "Overt Cat", "While other cats shy away into the shadows you can't help but be seen. At night you love getting on the phone and calling around to make sure people haven't forgotten you.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(86, "Courageous Puppy", "Puppies love early starts to the day and you are no exception. You are frequently on the phone and breakfast time is your favourite.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(87, "Dazzling Muskrat", "The most dazzling muskrat of all time, you shine brightest around lunch time on the weekends.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(88, "Typical Porpoise", "You might be frequently calling people but it certainly isn't work related. You enjoy your weekends, as would any normal porpoise.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(89, "Lucky Otter", "You have great friends and family and you do well at keeping in touch with them.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(90, "Didactic Panther", "As soon as night falls on the weekend you take charge. You want the night going your way and you aren't afraid to say it.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(91, "Burly Addax", "You rise early and the phone calls follow quickly. Your job keeps you on your toes but you stand strong.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(92, "Overconfident Aoudad", "Sheep aren't normally this confident but you defy all the odds. You make an intense number of calls over lunch.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(93, "Domineering Iguana", "Your calling style is wild and demanding. Come afternoon during the week you hit your calling peak.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(94, "Dazzling Whale", "You love a chat around dinner time during the week, and you do it quite a lot. Much like your plankton eating.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(95, "Noxious Liqueur", "Perhaps you are trying to break the drunken dialling record? You make a whole lot of calls at night during the week.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(96, "Noxious Jackhammer", "Right when people are trying to sleep in over the weekend you begin your phoning them all with reckless abandon. Sleeping in is nice, try it.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(97, "Dizzy Goat", "I would be dizzy too if I spent all day making as many phone calls as you. I'm impressed you haven't eaten your phone by accident yet, well done!", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(98, "Futuristic Serving Dish", "Your ability to call so many people in the afternoon can mean only one thing: You are from the future. Why you decided to come back as a serving dish is beyond me.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(99, "Abhorrent Soup", "There is nothing scarier then a dangerous soup. Your favourite time to strike is over dinner on the weekends… no surprises there", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(100, "Truculent Goblet", "Your phone likes to party hard and it won't let anyone get in its way. You are extremely active on the weekend at night", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.EVEN_CALLER));
		profiles.add(new Profile(101, "Tenuous Toothpaste", "I know if my toothpaste was this weak I wouldn't use it much either. Perhaps time for some new toothpaste.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(102, "Slow Chameleon", "Chameleons are already pretty slow creatures, but you are slower than the slowest, blending in over the week", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(103, "Habitual Fire Extinguisher", "Habits are always hard to kick but even harder when you are a fire extinguisher. Your habit is not calling anyone.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(104, "Evasive Hedgehog", "Hedgehogs are well known for their skilled evasive manoeuvres. Yours are so good you almost never have to use your phone.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(105, "Sable Rat", "Only rarely using your phone at night during the week, you avoid detection by staying mobile.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(106, "Evanescent Elf", "You use your phone so rarely that people might forget you even have one. Calling people in the morning on weekends doesn't help.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(107, "Absent Salamander", "Salamanders are not known for punctuality at the best of times. Anyone would be lucky if they heard from you at all…", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(108, "Dry Sticky Tape", "You only rarely use your phone and you are only usually making one off phone calls. You don't find your phone that useful.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(109, "Lackadaisical Ladle", "So unmotivated you rarely turn up for dinner, and only on the weekends at best. Come on! You lazy ladle.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(110, "Spurious Guinea", "You rarely calls others, but when you do, you can be sure it’s at night, on the weekends and when your BAC is at LEAST 0.25!", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.RARE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(111, "Scarce Coffee Pot", "Being a morning caller mainly you do like a good Coffee Pot, however you prefer to make sure your elbows are firmly attached before you start drinking.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(112, "Faulty Fish", "During the weekdays you seem to prefer to call people than eat your lunch. Probably a good thing considering 93% of people are poisoned during the lunch time.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(113, "Forgetful Budgerigar", "You would call people more often during the week if you could remember their names; however it's understandable to forget such a broad range of people", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(114, "Lopsided Moose", "You mostly call people during dinner time during the week. Shame on you! At least wait until they've eaten!", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(115, "Frail Wolverine", "At night you occasionally call… you find it tough though dialling with your adamantium claws.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(116, "Bumpy Vegetable Pattie", "Mostly calling in the mornings of the weekend, it can only be assumed you’re apologising for all the drunken things you did the night before", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(117, "Talented Crocodile", "Occasionally calling during lunch time on the weekends, you enjoy slow walks in the park and lazy Sunday afternoons with your soul mate", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(118, "Adaptable Puzzle", "Calling most often in the afternoon on weekends you like to be the person organising everything and everyone", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(119, "Jazzy Beaver", "Using your jazzy spirit fingers you quite often call people while their eating their dinners on the weekend", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(120, "Squalid Salamander", "Calling at night time on the weekends you’re a killer party animal… to bad that animal is a Salamander", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.OCCASIONAL_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(121, "Zippy Impala", "Whilst you do call an average amount of people, its lots of different people and most often in the morning on weekdays. Stop waking people up!", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(122, "Industrious Anteater", "Whilst munching down on some ants at lunch you tend to call an average amount of people, but only during the weekdays.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(123, "Verdant Elephant", "Similar to the giant Elephants, you mostly do you calling in the afternoon during the week calling a very broad range of people", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(124, "Flippant Cookbook", "Being a cookbook it’s understandable that most of your calls occur at dinner time during the week", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(125, "Rebel Remote Control", "As a rebel without a cause your night time weekday partying habits tend to influence your calling behaviour", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(126, "Ultra Toothpaste", "You seem to do most of your calling in the morning whilst brushing your teeth before you head out for weekend fun", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(127, "Majestic Albatross", "The Majestic Albatross does most of its calling at lunch time on the weekend. A rare and beautiful beast indeed", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(128, "Miniature Sugar Tongs", "For a miniature kitchen utensil you sure do make an average amount of phone calls in the afternoon on the weekends", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(129, "Fearless Cockatoo", "Calling a broad range of people quite often you mainly interrupt peoples dinners during the weekend to do so", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(130, "Deranged Futon", "At night… on your insane Futon you call… weekends only and to a broad range of people", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.AVERAGE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(131, "Fast 2-Prong Fork", "You call WAY too many people in the morning! Do them a favour and let them sleep in!", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(132, "Alert Coyote", "You call a large amount of people at lunch time during the week no doubt interrupting their breaks", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(133, "Gabby Monkey", "Frequently calling a broad range of people in the afternoon weekdays you are one crazy monkey", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(134, "Noxious Mynah", "Do you ever eat dinner? Really? Cause you seem to always be calling people during dinner time", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(135, "Lively Chameleon", "Calling every person you know at night time you certainly are lively!", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(136, "Heartbreaking Waffle", "Frequently calling people in the morning on the weekend, one can only assume their calls to apologies for the night before", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(137, "Energetic Alligator", "You certainly are energetic, calling so many people during the weekend lunch time period", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(138, "Good Pig", "In the afternoons of the weekend you constantly call anyone telling them their a BAD pig", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(139, "Whimsical Civet", "You never stop calling people during dinner time on the weekend. Maybe let them enjoy their dinner for once?", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(140, "Crazy Pirate Ship", "You attack in the night, pillaging towns all over the seven seas. You attack at night on weekends. Yarr!", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.FREQUENT_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(141, "Volatile Bath Towel", "You aren't the usual fluffy soft towel people were expecting, you are calling people early to ask them why you are out of soap.", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(142, "Tangy Doctor", "Doctors have flavours, yours is tangy. It's totally fact, I read about it on the internet.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(143, "Ultra Ram", "Ultra barely even cuts it. If there was a ramming contest you would win hands down. As long as the competition was in the afternoon.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(144, "Lethal Serving Fork", "Did you think serving forks were harmless? You thought wrong. You a living proof that dinner time can be deadly.", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(145, "Abandoned Puma", "A wildcat with no boundaries. When the sun goes down anyone is a target. Who you are going to call next is anyone’s guess.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKDAY_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(146, "Boiling Mountain", "You are a force to be reckoned with. Who has time for breakfast or a sleep in when there are calls to be made?", R.drawable.icon, Profile.MORNING_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(147, "Burly Hartebeest", "You wouldn't walk into a room without everyone knowing about it. Most likely because you called them all ahead of time.", R.drawable.icon, Profile.LUNCH_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(148, "Scandalous Gemsbok", "If there is a scandal you know about it, probably because most the time you are involved. Gemsboks are crazy like that.", R.drawable.icon, Profile.AFTERNOON_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(149, "Overwrought Kangaroo", "You work hard to maintain your lifestyle, jumping around like a mad person just to get through a weekend", R.drawable.icon, Profile.DINNER_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));
		profiles.add(new Profile(150, "Wrathful Pillowcase", "You prefer to catch your victims while they sleep… Your wrath spreads far and wide.", R.drawable.icon, Profile.NIGHT_CALLER, Profile.WEEKEND_CALLER, Profile.INTENSE_CALLER, Profile.BROAD_CALLER));

	}
	
	public Profile getProfile(int profileID) {
		for(int i = 0; i < profiles.size(); i++) {
			Profile profile = profiles.get(i);
			if(profile.getProfileID() == profileID) {
				return profile;
			}
		}
		return null;
	}
	
	public Profile getMatchingProfile(int timeOfDayType, int dayOfWeekType, int callAmountType, int callVariationType) {
		for(int i = 0; i < profiles.size(); i++) {
			Profile profile = profiles.get(i);
			if(profile.getTimeOfDayType() == timeOfDayType && 
					profile.getDayOfWeekType() == dayOfWeekType &&
					profile.getCallAmountType() == callAmountType &&
					profile.getCallVariationType() == callVariationType) {
				return profile;
			}
		}
		return null;
	}
}
